# Generated by Django 5.0.3 on 2024-04-02 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_item_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='user',
        ),
    ]
